version: 2
updates:
  - package-ecosystem: "docker"
    assignees: [astrovm]
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    assignees: [astrovm]
    directory: "/"
    schedule:
      interval: "weekly"
